services:
  web:  # 開発中アプリ
    build: .
    command: bundle exec bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - ./storage:/app/storage
    ports:
      - "3001:3000"  # ホスト側 3001 → コンテナ側 3000
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: training_manager_development
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: training_manager_development
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
  bundle: {}
