services:
  web:
    build: .
    env_file:
      - .env
    command: bundle exec bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - ./storage:/app/storage
    expose:
      - "3000" 
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: training_manager_development

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: training_manager_development
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # ローカルブラウザからアクセス
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  db-data: {}
  bundle: {}

