default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "training_manager_development") %>

test:
  <<: *default
  database: app_test

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    host: <%= ENV.fetch("DATABASE_HOST") %>
    username: <%= ENV.fetch("DATABASE_USER") %> # 環境変数から取得
    password: <%= ENV.fetch("APP_DATABASE_PASSWORD") %> # ここだけ正しく指定
    database: <%= ENV.fetch("DATABASE_NAME") %>
    pool: 5
  cache:
    <<: *primary_production
    database: app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: app_production_cable
    migrations_paths: db/cable_migrate
